globalThis.WEAVE_WORKFLOWS = Object.freeze({
  finance: {
    label: "Finance",
    title: "Publish a board-ready forecast",
    description: "Inspect source data and assumptions in parallel. Nothing is delivered until the model, dashboard, and reconciliation check agree.",
    result: "Forecast pack with approved assumptions and reconciled totals",
    nodes: [
      { id: "brief", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Set forecast scope" },
      { id: "inspect", x: 220, y: 92, kind: "work", eyebrow: "Codex", title: "Inspect workbook" },
      { id: "assumptions", x: 220, y: 324, kind: "work", eyebrow: "Codex", title: "Map assumptions" },
      { id: "approve", x: 414, y: 208, kind: "human", eyebrow: "Your call", title: "Approve assumptions" },
      { id: "model", x: 610, y: 62, kind: "work", eyebrow: "Codex", title: "Build model" },
      { id: "dashboard", x: 610, y: 208, kind: "work", eyebrow: "Codex", title: "Build dashboard" },
      { id: "reconcile", x: 610, y: 354, kind: "check", eyebrow: "Exact check", title: "Reconcile totals" },
      { id: "verify", x: 808, y: 208, kind: "verify", eyebrow: "Review", title: "Verify the pack" },
      { id: "deliver", x: 992, y: 208, kind: "output", eyebrow: "Result", title: "Board pack" },
    ],
    edges: [
      ["brief", "inspect"], ["brief", "assumptions"], ["inspect", "approve"], ["assumptions", "approve"],
      ["approve", "model"], ["approve", "dashboard"], ["approve", "reconcile"], ["model", "verify"],
      ["dashboard", "verify"], ["reconcile", "verify"], ["verify", "deliver"],
    ],
  },
  frontend: {
    label: "Frontend",
    title: "Redesign a checkout without guessing",
    description: "Audit the product and its design system together. Choose the direction before implementation, then require two independent reviews.",
    result: "Implemented checkout with accessibility and visual evidence",
    nodes: [
      { id: "goal", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Define outcome" },
      { id: "flow", x: 214, y: 92, kind: "work", eyebrow: "Codex", title: "Audit user flow" },
      { id: "system", x: 214, y: 324, kind: "work", eyebrow: "Codex", title: "Audit design system" },
      { id: "concepts", x: 400, y: 208, kind: "work", eyebrow: "Codex", title: "Draft two routes" },
      { id: "choose", x: 582, y: 208, kind: "human", eyebrow: "Your call", title: "Choose direction" },
      { id: "shell", x: 760, y: 92, kind: "work", eyebrow: "Codex", title: "Build interface" },
      { id: "states", x: 760, y: 324, kind: "work", eyebrow: "Codex", title: "Build interactions" },
      { id: "a11y", x: 946, y: 92, kind: "check", eyebrow: "Exact check", title: "Run accessibility" },
      { id: "visual", x: 946, y: 324, kind: "verify", eyebrow: "Review", title: "Visual review" },
      { id: "release", x: 1128, y: 208, kind: "output", eyebrow: "Result", title: "Release candidate" },
    ],
    edges: [
      ["goal", "flow"], ["goal", "system"], ["flow", "concepts"], ["system", "concepts"],
      ["concepts", "choose"], ["choose", "shell"], ["choose", "states"], ["shell", "a11y"],
      ["states", "visual"], ["a11y", "release"], ["visual", "release"],
    ],
  },
  incident: {
    label: "Incident response",
    title: "Repair a production incident with a visible gate",
    description: "Collect evidence before diagnosis. Approve the repair plan before any change, then combine the patch and safety review in one regression gate.",
    result: "Verified repair and a concise incident record",
    nodes: [
      { id: "alert", x: 28, y: 208, kind: "input", eyebrow: "Signal", title: "Define incident" },
      { id: "logs", x: 220, y: 92, kind: "work", eyebrow: "Codex", title: "Collect evidence" },
      { id: "reproduce", x: 220, y: 324, kind: "work", eyebrow: "Codex", title: "Reproduce issue" },
      { id: "diagnose", x: 414, y: 208, kind: "work", eyebrow: "Codex", title: "Diagnose cause" },
      { id: "approve", x: 610, y: 208, kind: "human", eyebrow: "Your call", title: "Approve repair" },
      { id: "patch", x: 804, y: 92, kind: "work", eyebrow: "Codex", title: "Patch in sandbox" },
      { id: "review", x: 804, y: 324, kind: "verify", eyebrow: "Review", title: "Check safety" },
      { id: "regression", x: 998, y: 208, kind: "check", eyebrow: "Exact check", title: "Run regression" },
      { id: "note", x: 1145, y: 208, kind: "output", eyebrow: "Result", title: "Incident record" },
    ],
    edges: [
      ["alert", "logs"], ["alert", "reproduce"], ["logs", "diagnose"], ["reproduce", "diagnose"],
      ["diagnose", "approve"], ["approve", "patch"], ["approve", "review"], ["patch", "regression"],
      ["review", "regression"], ["regression", "note"],
    ],
  },
});
